import Head from "next/head";
import { SignIn } from "../components/SignIn";

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>
      <SignIn />
    </div>
  </>
);

export default Home;
